apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aerostream-ingress
  namespace: aerostream
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: ui.localdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  number: 8080

    - host: api.localdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8080