apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: aerostream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api
          image: aerostream-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: Kafka__BootstrapServers
              value: "kafka-service:9092"
            - name: Kafka__Topic
              value: "telemetry-stream"
            - name: Postgres__ConnectionString
              value: "Host=postgres;Port=5432;Database=telemetrydb;Username=admin;Password=admin123"
            - name: OpenSearch__Url
              value: "http://opensearch:9200"
            - name: Redis__Connection
              value: "redis:6379"
            - name: AzureAd__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: aerostream-app-secrets
                  key: azure-api-clientSecret
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"