apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: aerostream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-deployment
  template:
    metadata:
      labels:
        app: worker-deployment
    spec:
      containers:
        - name: worker
          image: aerostream-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: Kafka__BootstrapServers
              value: "kafka-service:9092"
            - name: Kafka__Topic
              value: "telemetry-stream"
            - name: Postgres__ConnectionString
              value: "Host=postgres;Port=5432;Database=telemetrydb;Username=admin;Password=admin123"
            - name: OpenSky__ClientId
              valueFrom:
                secretKeyRef:
                  name: aerostream-app-secrets
                  key: opensky-clientId
            - name: OpenSky__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: aerostream-app-secrets
                  key: opensky-clientSecret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"