apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: aerostream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aerostream-worker
  template:
    metadata:
      labels:
        app: aerostream-worker
    spec:
      containers:
        - name: worker
          image: aerostream-worker:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"